osx_image: xcode9.3

dist: trusty
sudo: false

language: node_js

node_js:
  - 8

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mono
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso
      - mono-devel

install:
  - export CXX="g++-4.8"
  - npm install
  - cd app && npm install && cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16; fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - node --version
  - export NODE_ENV=test
  - npm run lint
  - npm run package
  - npm run test
  - npm run test-e2e
